"""Gzips web/ into src/net/WebAssets.h so the portal ships inside the firmware
(PLAN.md §4.9: an OTA update always carries a matching UI).

Runs as a PlatformIO pre-script; also runnable on its own: python scripts/embed_web.py
The header is rewritten only when its content changes, so builds stay incremental.
"""

import gzip
import pathlib

try:
    Import("env")  # noqa: F821 (provided by PlatformIO)
    PROJECT = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
except NameError:
    PROJECT = pathlib.Path(__file__).resolve().parent.parent

SOURCE = PROJECT / "web"
OUTPUT = PROJECT / "src" / "net" / "WebAssets.h"
MIME = {
    ".html": "text/html; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
}


def identifier(path):
    return "k" + "".join(c if c.isalnum() else "_" for c in path.name)


def render():
    files = sorted(p for p in SOURCE.iterdir() if p.suffix in MIME)
    out = [
        "#pragma once",
        "// Generated by scripts/embed_web.py from web/. Do not edit.",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace web {",
        "",
        "struct Asset {",
        "  const char *path;",
        "  const char *mime;",
        "  const uint8_t *data;  // gzip",
        "  size_t length;",
        "};",
        "",
    ]
    table = []
    total = 0
    for path in files:
        data = gzip.compress(path.read_bytes(), compresslevel=9, mtime=0)
        total += len(data)
        name = identifier(path)
        out.append(f"// {path.name}: {path.stat().st_size} bytes, {len(data)} gzipped")
        out.append(f"static const uint8_t {name}[] = {{")
        for i in range(0, len(data), 20):
            out.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 20]) + ",")
        out.append("};")
        out.append("")
        table.append(f'  {{"/{path.name}", "{MIME[path.suffix]}", {name}, sizeof({name})}},')
    out.append("static const Asset kAssets[] = {")
    out.extend(table)
    out.append("};")
    out.append("")
    out.append("}  // namespace web")
    out.append("")
    return "\n".join(out), len(files), total


def main():
    text, count, total = render()
    old = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if text != old:
        OUTPUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"embed_web: {count} files, {total} bytes gzipped -> {OUTPUT.relative_to(PROJECT)}")


main()
